package org.rta.rules.fee.refreshrc.transport
 
import org.rta.rules.model.FeeRuleModel;
 
 
rule "PR Service charge Fresh RC for Financer  transport Fee MMCN~MCYN"
salience 82    
    when
        t : FeeRuleModel("MMCN~MCYN".contains(vehicleClassCategory) , prService == 0 ) 
    then
        System.out.println("Inside PR service charge Fresh RC for Financer  transport MMCN~MCYN");
        t.setPrService(150);
        update( t );
end


rule "PR 300 rs Service charge Fresh RC for Financer  transport"
salience 80    
    when
        t : FeeRuleModel(prService == 0 ) 
    then
        System.out.println("Inside PR 300 rs service charge Fresh RC for Financer  transport");
        t.setPrService(300);
        update( t );
end
 

rule "Total PR Fee Fresh RC for Financer  transport Fee"
    when
        t : FeeRuleModel(totalPrFee == 0 )
    then
        System.out.println("Inside Total PR Fee Fresh RC for Financer  transport "+ t.getVehicleClassCategory());
        t.setTotalPrFee(t.getPrService() );
        update( t );
end