package org.rta.rules.fee.hpa.nontransport
 
import org.rta.rules.model.FeeRuleModel;

rule "Card Fee 200 rs  HPA non transport Fee"
salience 100
    when
        t : FeeRuleModel(cardFee == 0 , "TRCN~TRCN~TRCN~TTRN~TTRN~TTRN" not contains vehicleClassCategory) 
    then
        System.out.println("Card Fee 200 rs HPA non transport Fee");
        t.setCardFee(200);
        update( t );
end

rule "Postal 35 HPA non transport Fee"
salience 90
    when
        t : FeeRuleModel(postalFee == 0 ) 
    then
        System.out.println("Postal Fee HPA non transport");
        t.setPostalFee(35);
        update( t );
end

 
rule "PR Service charge HPA non  transport Fee MMCN~MCYN"
salience 82    
    when
        t : FeeRuleModel("MMCN~MCYN".contains(vehicleClassCategory) , prService == 0 ) 
    then
        System.out.println("Inside PR service charge HPA non transport MMCN~MCYN");
        t.setPrService(150);
        update( t );
end


rule "PR 300 rs Service charge HPA non transport"
salience 80    
    when
        t : FeeRuleModel(prService == 0 ) 
    then
        System.out.println("Inside PR 300 rs service charge HPA non  transport");
        t.setPrService(300);
        update( t );
end
 

rule "MMCN LMV and MMV HPAnon transport Fee"
    when
        t : FeeRuleModel("MMCN~MCYN".contains(vehicleClassCategory) , prFee == 0 , gvw < 12000)
    then
        System.out.println("Inside LMV and MMV HPA non transport MMCN MCYN");
        t.setPrFee(500);
        update( t );
end

rule "LMV HPA non transport Fee"
    when
        t : FeeRuleModel( prFee == 0 , gvw < 7500 )
    then
        System.out.println("Inside LMV HPA non transport");
        t.setPrFee(1500);
        update( t );
end

rule "MMV and MMV HPA non transport Fee"
    when
        t : FeeRuleModel( prFee == 0 , gvw > 7500 )
    then
        System.out.println("Inside MMV and HMV HPA non transport");
        t.setPrFee(3000);
        update( t );
end



rule "Total PR Fee HPA non transport Fee"
    when
        t : FeeRuleModel(totalPrFee == 0 )
    then
        System.out.println("Inside Total PR Fee HPA non  transport "+ t.getVehicleClassCategory());
        t.setTotalPrFee(t.getPrFee() + t.getPrService() + t.getPostalFee() + t.getCardFee());
        update( t );
end