package org.rta.rules.fee.alterationvehicle.nontransport
 
import org.rta.rules.model.FeeRuleModel;

 
rule "Card Fee 200 rs  alteration of vehicle non transport Fee"
salience 100
    when
        t : FeeRuleModel(cardFee == 0 , "TRCN~TRCN~TRCN~TTRN~TTRN~TTRN" not contains vehicleClassCategory) 
    then
        System.out.println("Card Fee 200 rs alteration of vehicle non transport Fee");
        t.setCardFee(200);
        update( t );
end


rule "Postal 35 alteration of vehicle non transport Fee"
salience 90
    when
        t : FeeRuleModel(postalFee == 0 , "TRCN" not contains vehicleClassCategory) 
    then
        System.out.println("Postal Fee alteration of vehicle non transport");
        t.setPostalFee(35);
        update( t );
end


rule "PR Service charge alteration of vehicle non transport Fee MMCN~MCYN"
salience 82    
    when
        t : FeeRuleModel("MMCN~MCYN".contains(vehicleClassCategory) , prService == 0 ) 
    then
        System.out.println("Inside PR service charge alteration of vehicle non transport MMCN~MCYN");
        t.setPrService(150);
        update( t );
end


rule "PR 300 rs Service charge alteration of vehicle non transport"
salience 80    
    when
        t : FeeRuleModel(prService == 0 ) 
    then
        System.out.println("Inside PR 300 rs service charge alteration of vehicle non transport");
        t.setPrService(300);
        update( t );
end


rule "IVCN alteration of vehicle non transport Fee"
    when
        t : FeeRuleModel(vehicleClassCategory.equals("IVCN") , prFee == 0)
    then
        System.out.println("Inside alteration of vehicle non transport IVCN");
        t.setPrFee(150);
        update( t );
end


rule "SLCM LMV alteration of vehicle non transport Fee"
    when
        t : FeeRuleModel(vehicleClassCategory.equals("SLCM") , prFee == 0 , gvw <= 7500)
    then
        System.out.println("Inside LMV alteration of vehicle non transport SLCM");
        t.setPrFee(50);
        update( t );
end


rule "300 rs alteration of vehicle non transport Fee"
    when
        t : FeeRuleModel("DEXT~CVPN~ARPN~BRVN~CTPN~CTPN~CHSN~CMPN~CRNN~CRMN~DMPN~DEXN~EXCN~FRLN~GEMN~JEPN~LODN~MSVN~MCRN~MGRN~OBPN~OTPN~REVN~RIGN~RRLN~SPHN~SWPN~TWVN~TOTN~TOWN~ATCHN~TRCN~TATN~TTRN~TCPN~TTVN~TMVN~CEHHN".contains(vehicleClassCategory) , prFee == 0 ,gvw <= 7500) 
    then
        System.out.println("Inside 300 rs alteration of vehicle non transport Fee ");
        t.setPrFee(300);
        update( t );	
end



rule "MMV alteration of vehicle non transport Fee"
    when
        t : FeeRuleModel( prFee == 0 , gvw > 7500 , gvw < 12000)
    then
        System.out.println("Inside MMV alteration of vehicle non transport");
        t.setPrFee(500);
        update( t );
end


rule "HMV alteration of vehicle non transport Fee"
    when
        t : FeeRuleModel( prFee == 0 , gvw > 12000)
    then
        System.out.println("Inside HMV alteration of vehicle non transport ");
        t.setPrFee(750);
        update( t );
end

rule "MCYN LMV alteration of vehicle non transport Fee"
    when
        t : FeeRuleModel(vehicleClassCategory.equals("MCYN") , prFee == 0 )
    then
        System.out.println("Inside  alteration of vehicle non transport MCYN");
        t.setPrFee(150);
        update( t );
end


rule "Special number alteration NonTransport Fee"
    when
        t : FeeRuleModel(specialNoFlag == 2 , specialNumberFee == 0 )
    then
        System.out.println("Inside Special number alteration NonTransport Fee");
        t.setSpecialNumberFee(100);
        update( t );
end


rule "Total PR Fee alteration of vehicle non transport Fee"
    when
        t : FeeRuleModel(totalPrFee == 0 )
    then
        System.out.println("Inside Total PR Fee alteration of vehicle non transport "+ t.getVehicleClassCategory());
        t.setTotalPrFee(t.getPrFee() + t.getPrService() + t.getPostalFee() + t.getCardFee() + t.getSpecialNumberFee());
        update( t );
end
