package org.rta.rules.fee.duplicateregist.transport
 
import org.rta.rules.model.FeeRuleModel;
 
 
 rule "PR Service charge Duplicate registration non transport Fee MMCN~MCYN"
salience 82    
    when
        t : FeeRuleModel("ARKT".contains(vehicleClassCategory) , prService == 0 ) 
    then
        System.out.println("Inside PR service charge Duplicate registration non transport MMCN~MCYN");
        t.setPrService(150);
        update( t );
end


rule "PR 300 rs Service charge Duplicate registration non transport"
salience 80    
    when
        t : FeeRuleModel(prService == 0 ) 
    then
        System.out.println("Inside PR 300 rs service charge Duplicate registration non transport");
        t.setPrService(300);
        update( t );
end


rule "300 rs Duplicate registration  transport Fee"
    when
        t : FeeRuleModel("ARKT".contains(vehicleClassCategory) , prFee == 0 ,gvw <= 12000) 
    then
        System.out.println("Inside 25 rs Duplicate registration  transport Fee ");
        t.setPrFee(300);
        update( t );
end

rule "500 rs LMV Duplicate registration  transport Fee"
    when
        t : FeeRuleModel(prFee == 0 ,gvw <= 12000 , "CHST" not contains vehicleClassCategory) 
    then
        System.out.println("Inside 500 rs LMV Duplicate registration  transport Fee ");
        t.setPrFee(500);
        update( t );
end


rule "750 rs HMV Duplicate registration  transport Fee"
    when
        t : FeeRuleModel(prFee == 0 ,gvw > 12000 , "CHST" not contains vehicleClassCategory) 
    then
        System.out.println("Inside 750 rs HMV Duplicate registration  transport Fee ");
        t.setPrFee(750);
        update( t );
end


rule "Total PR Fee Duplicate registration  transport Fee"
    when
        t : FeeRuleModel(totalPrFee == 0 )
    then
        System.out.println("Inside Total PR Fee Duplicate registration  transport "+ t.getVehicleClassCategory());
        t.setTotalPrFee(t.getPrFee() + t.getPrService() + t.getPostalFee() + t.getCardFee());
        update( t );
end