package org.rta.rules.fee.cancelnoc.transport
 
import org.rta.rules.model.FeeRuleModel;

 
rule "PR Service charge Cancelltaion of NOC  transport Fee MMCN~MCYN"
salience 82    
    when
        t : FeeRuleModel("ARKT".contains(vehicleClassCategory) , prService == 0 ) 
    then
        System.out.println("Inside PR service charge Cancelltaion of NOC  transport MMCN~MCYN");
        t.setPrService(150);
        update( t );
end


rule "PR 300 rs Service charge Cancelltaion of NOC  transport"
salience 80    
    when
        t : FeeRuleModel(prService == 0 ) 
    then
        System.out.println("Inside PR 300 rs service charge Cancelltaion of NOC  transport");
        t.setPrService(100);
        update( t );
end

rule "Total PR Fee Cancelltaion of NOC  transport Fee"
    when
        t : FeeRuleModel(totalPrFee == 0 )
    then
        System.out.println("Inside Total Cancelltaion of NOC non transport "+ t.getVehicleClassCategory());
        t.setTotalPrFee(t.getPrService());
        update( t );
end