package org.rta.rules.fee.changeaddress.nontransport
 
import org.rta.rules.model.FeeRuleModel;

 
rule "PR Service charge Change of address non transport Fee MMCN~MCYN"
salience 82    
    when
        t : FeeRuleModel("MMCN~MCYN".contains(vehicleClassCategory) , prService == 0 ) 
    then
        System.out.println("Inside PR service charge Change of address non transport MMCN~MCYN");
        t.setPrService(150);
        update( t );
end


rule "PR 300 rs Service charge Change of address non transport"
salience 80    
    when
        t : FeeRuleModel(prService == 0 ) 
    then
        System.out.println("Inside PR 300 rs service charge Change of address non transport");
        t.setPrService(300);
        update( t );
end
 
rule "Postal 35 Change of address non transport Fee"
salience 100
    when
        t : FeeRuleModel(postalFee == 0 ) 
    then
        System.out.println("Postal Fee Change of address non transport");
        t.setPostalFee(35);
        update( t );
end


rule "Card Fee 200 rs  Change of address non transport Fee"
salience 90
    when
        t : FeeRuleModel(cardFee == 0 , "TRCN~TRCN~TRCN~TTRN~TTRN~TTRN" not contains vehicleClassCategory) 
    then
        System.out.println("Card Fee 200 rs Change of address non transport Fee");
        t.setCardFee(200);
        update( t );
end


rule "25 rs Change of address non transport Fee"
    when
        t : FeeRuleModel("IVCN~MMCN".contains(vehicleClassCategory) , prFee == 0 ,gvw <= 7500) 
    then
        System.out.println("Inside 25 rs Change of address non transport Fee ");
        t.setPrFee(25);
        update( t );
end

rule "MCYN LMV Change of address non transport Fee"
    when
        t : FeeRuleModel(vehicleClassCategory.equals("MCYN") , prFee == 0 )
    then
        System.out.println("Inside  Change of address non transport MCYN");
        t.setPrFee(150);
        update( t );
end


rule "300 rs LMV Change of address non transport Fee"
    when
        t : FeeRuleModel(prFee == 0 ,gvw <= 7500 , "CHST" not contains vehicleClassCategory) 
    then
        System.out.println("Inside 300 rs LMV Change of address non transport Fee ");
        t.setPrFee(300);
        update( t );
end

rule "SLCM MMV Change of address non transport Fee"
    when
        t : FeeRuleModel(vehicleClassCategory.equals("SLCM") , prFee == 0 , gvw <= 12000)
    then
        System.out.println("Inside MMV and LMV Change of address non transport SLCM");
        t.setPrFee(500);
        update( t );
end

rule "1500 rs MMV and HMV Change of address non transport Fee"
    when
        t : FeeRuleModel(prFee == 0 ,gvw > 7500 , "CHST" not contains vehicleClassCategory) 
    then
        System.out.println("Inside 1500 rs MMV Change of address non transport Fee ");
        t.setPrFee(1500);
        update( t );
end

rule "SLCM HMV Change of address non transport Fee"
    when
        t : FeeRuleModel(vehicleClassCategory.equals("SLCM") , prFee == 0 , gvw > 12000)
    then
        System.out.println("Inside HMV Change of address non transport SLCM");
        t.setPrFee(750);
        update( t );
end


rule "Penalty Change of address non transport  old vehicle 0 to 3"
    when
        t : FeeRuleModel( oldVehicle , penalty == 0 , monthCount > 0 , monthCount < 4 )
    then
        System.out.println("Penalty Change of address non transport Fee  old vehicle 0 to 3 ");
        t.setPenalty(25);
        update( t );
end

rule "Penalty Change of address non transport two wheller old vehicle 4 to 6"
    when
        t : FeeRuleModel( oldVehicle , penalty == 0 , monthCount > 3 , monthCount < 7)
    then
        System.out.println("Penalty Change of address non transport Fee  old vehicle 4 to 6");
        t.setPenalty(50);
        update( t );
end

rule "Penalty Change of address non transport two wheller old vehicle 7 to 9"
    when
        t : FeeRuleModel( oldVehicle , penalty == 0 , monthCount > 6 , monthCount < 10 )
    then
        System.out.println("Penalty Change of address non transport Fee  old vehicle 7 to 9");
        t.setPenalty(75);
        update( t );
end

rule "Penalty Change of address non transport two wheller old vehicle greater than 10"
    when
        t : FeeRuleModel( oldVehicle , penalty == 0 , monthCount > 9 )
    then
        System.out.println("Penalty Change of address non transport Fee  old vehicle greater than 10");
        t.setPenalty(100);
        update( t );
end

rule "Penalty Change of address non transport two wheller new vehicle "
    when
        t : FeeRuleModel( !oldVehicle , penalty == 0 , monthCount >0 ,"MMCN~MCYN~MCWN" contains vehicleClassCategory)
    then
        System.out.println("Penalty Change of address non transport Fee two wheller  vehicle ");
        t.setPenalty(300*t.getMonthCount());
        update( t );
end


rule "Penalty Change of address non transport other wheller new vehicle "
    when
        t : FeeRuleModel( !oldVehicle , penalty == 0 , monthCount >0 ,"MMCN~MCYN~MCWN" not contains vehicleClassCategory)
    then
        System.out.println("Penalty Change of address non transport Fee other wheller  vehicle ");
        t.setPenalty(500*t.getMonthCount());
        update( t );
end


rule "Total PR Fee Change of address non transport Fee"
    when
        t : FeeRuleModel(totalPrFee == 0 )
    then
        System.out.println("Inside Total PR Fee Change of address non transport "+ t.getVehicleClassCategory());
        t.setTotalPrFee(t.getPrFee() + t.getPrService() + t.getPostalFee() + t.getCardFee() + t.getPenalty());
        update( t );
end