package org.rta.rules.fee.hpt.transport
 
import org.rta.rules.model.FeeRuleModel;
 
rule "PR Service charge HPT   transport Fee ARKT"
salience 82    
    when
        t : FeeRuleModel("ARKT".contains(vehicleClassCategory) , prService == 0 ) 
    then
        System.out.println("Inside PR service charge HPT  transport ARKT");
        t.setPrService(150);
        update( t );
end


rule "PR 300 rs Service charge HPT  transport"
salience 80    
    when
        t : FeeRuleModel(prService == 0 ) 
    then
        System.out.println("Inside PR 300 rs service charge HPT   transport");
        t.setPrService(300);
        update( t );
end
 

rule "Total PR Fee HPT  transport Fee"
    when
        t : FeeRuleModel(totalPrFee == 0 )
    then
        System.out.println("Inside Total PR Fee HPT   transport "+ t.getVehicleClassCategory());
        t.setTotalPrFee(t.getPrService() );
        update( t );
end