package org.rta.rules.fee.hpt.nontransport
 
import org.rta.rules.model.FeeRuleModel;

 
rule "Card Fee 200 rs  HPT non transport Fee"
salience 100
    when
        t : FeeRuleModel(cardFee == 0 , "TRCN~TRCN~TRCN~TTRN~TTRN~TTRN" not contains vehicleClassCategory) 
    then
        System.out.println("Card Fee 200 rs HPT non transport Fee");
        t.setCardFee(200);
        update( t );
end

rule "Postal 35 HPT non transport Fee"
salience 90
    when
        t : FeeRuleModel(postalFee == 0 ) 
    then
        System.out.println("Postal Fee HPT non transport");
        t.setPostalFee(35);
        update( t );
end

 
rule "PR Service charge HPT non  transport Fee MMCN~MCYN"
salience 82    
    when
        t : FeeRuleModel("MMCN~MCYN".contains(vehicleClassCategory) , prService == 0 ) 
    then
        System.out.println("Inside PR service charge HPT non transport MMCN~MCYN");
        t.setPrService(150);
        update( t );
end


rule "PR 300 rs Service charge HPT non transport"
salience 80    
    when
        t : FeeRuleModel(prService == 0 ) 
    then
        System.out.println("Inside PR 300 rs service charge HPT non  transport");
        t.setPrService(300);
        update( t );
end
 


rule "Total PR Fee HPT non transport Fee"
    when
        t : FeeRuleModel(totalPrFee == 0 )
    then
        System.out.println("Inside Total PR Fee HPT non  transport "+ t.getVehicleClassCategory());
        t.setTotalPrFee(t.getPrFee() + t.getPrService() + t.getPostalFee() + t.getCardFee());
        update( t );
end