package org.rta.rules.fee.permit.renewalauth
 
import org.rta.rules.model.FeeRuleModel;
 
rule "Permit renewalauth Fee Service chage 150 rs"
salience 89
    when
        t : FeeRuleModel(permitService == 0) 
    then
        System.out.println("Permit Service charge 100 rs Fresh Registration NonTransport Fee");
        t.setPermitService(150);
        update( t );
end


rule "Permit renewalauth Fee AITC Authorization fee 1000 rs "
    when
        t : FeeRuleModel("AITC~AITP" contains permitType  , otherPermitFee == 0) 
    then
        System.out.println("Inside renewalauth 500 rs Authorization  Fee AITC");
        t.setOtherPermitFee(500);
        update( t );
end

rule "Permit renewalauth Fee NP Authorization fee 1000 rs "
    when
        t : FeeRuleModel("NP" contains permitType  , otherPermitFee == 0 , "GCRT~ARVT~TTTT"  contains vehicleClassCategory) 
    then
        System.out.println("Inside renewalauth 1000 rs Authorization  Fee NP");
        t.setOtherPermitFee(1000);
        update( t );
end

rule "Penalty renewalauth Permit "
    when
        t : FeeRuleModel(penalty == 0 ,  monthCount > 0 )
    then
        System.out.println("Penalty renewalauth Permit Fee two wheller old vehicle 0 to 3 ");
        t.setPenalty(15*t.getMonthCount());
        update( t );
end


rule "Total renewalauth New Permit Fee "
    when
        t : FeeRuleModel(totalPermitFee == 0)
    then
        System.out.println("Inside renewalauth Total Permit Fee "+ t.getVehicleClassCategory() +"  "+ t.getPermitType());
        t.setTotalPermitFee( t.getPermitService() + t.getOtherPermitFee() +  t.getPenalty());
        update( t );
end
