package org.rta.rules.fee.reassignvehicle.transport
 
import org.rta.rules.model.FeeRuleModel;
 
 
rule "PR 150 Service charge Reassignment of vehicle   transport Fee ARKT"
salience 82    
    when
        t : FeeRuleModel("ARKT".contains(vehicleClassCategory) , prService == 0 ) 
    then
        System.out.println("Inside PR service charge Reassignment of vehicle  transport ARKT");
        t.setPrService(150);
        update( t );
end

rule "PR 300 rs Service charge Reassignment of vehicle  transport"
salience 80    
    when
        t : FeeRuleModel(prService == 0 ) 
    then
        System.out.println("Inside PR 300 rs service charge Reassignment of vehicle   transport");
        t.setPrService(300);
        update( t );
end
 

rule "LMV Reassignment of vehicle  transport Fee"
    when
        t : FeeRuleModel( prFee == 0 , gvw < 12000 ,"CHST" not contains vehicleClassCategory )
    then
        System.out.println("Inside LMV Reassignment of vehicle  transport");
        t.setPrFee(1000);
        update( t );
end


rule "HMV Reassignment of vehicle  transport Fee"
    when
        t : FeeRuleModel( prFee == 0 , gvw > 12000  , "CHST" not contains vehicleClassCategory)
    then
        System.out.println("Inside HMV Reassignment of vehicle  transport");
        t.setPrFee(3000);
        update( t );
end

rule "Total PR Fee Reassignment of vehicle  transport Fee"
    when
        t : FeeRuleModel(totalPrFee == 0 )
    then
        System.out.println("Inside Total PR Fee Reassignment of vehicle   transport "+ t.getVehicleClassCategory());
        t.setTotalPrFee(t.getPrFee() + t.getPrService() + t.getPostalFee() + t.getCardFee());
        update( t );
end